### ISSUE TITLE
Date Filter

### ISSUE THREAD

**Issue by okpatil4u** [httpjamesm/kagigo#1]
Hello @httpjamesm, is date filter enabled in this API ? How would one go about implementing it ?

**Comment by httpjamesm** [comment]
I'm not sure what you mean. Which API specifically are you referring to?

**Comment by okpatil4u** [comment]
My apologies, I meant search API.

curl -v \
  -H "Authorization: Bot $TOKEN" \
  https://kagi.com/api/v0/search\?q\=steve+jobs\&dr\=1

This is the query I am trying to run.

**Comment by httpjamesm** [comment]
Kagigo does not support the search API currently as it's enterprise only.

**Comment by httpjamesm** [comment]
Irrelevant
